spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qiaomu_service?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    open: true  # 是否开启redis缓存  true开启   false关闭
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

#### 上传文件保存的路径
file:
  save: E:/files/

logging:
  level:
    root: debug
  path: logs/
  file: websocket_info.log
  config: classpath:logback-spring.xml

netty-config:
  port: 8090
  isDistributed: true
  ssl: false
  webSocketPath: /nettySocket
  serverName: iot-netty-chat
  backlog: 2048