# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /Websocket

spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect



